import Link from "next/link"
import { Metadata } from "next"
// async function getData() {
//   const response = await fetch(
//     "https://jsonplaceholder.typicode.com/posts"
//   ).then((res) => res.json())
//   return response
// }

export const metadata: Metadata = {
  title: "Blog | Next App",
  description: "Generated by create next app",
}

const getData = async () => {
  const response = await fetch(
    "https://jsonplaceholder.typicode.com/posts"
  ).then((res) => res.json())
  return response
}

export default async function Blog() {
  let data = await getData()
  console.log("data: ", data)
  return (
    <>
      <h1>Blog</h1>
      <ul>
        {data.map((item: any) => (
          <li key={item.id}>
            <Link href={`/blog/${item.id}`}>{item.title}</Link>
          </li>
        ))}
      </ul>
    </>
  )
}
