import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { TheFooter } from "@/components/TheFooter/TheFooter"
import { TheHeader } from "@/components/TheHeader/TheHeader"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapp">
          <TheHeader />
          <div className="container">
            <main>{children}</main>
          </div>
          <div>
            <TheFooter />
          </div>
        </div>
      </body>
    </html>
  )
}
